export const ADJUST_EMOTION_VALUE = 'ADJUST_EMOTIONS';
export const LOCATION_INPUT_CHANGE = 'LOCATION_INPUT_CHANGE';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_LOCATION_FAILED = 'SET_LOCATION_FAILED';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_WEATHER_FAILED = 'SET_WEATHER_FAILED';
